package com.aturzone.chaos

import android.Manifest
import android.annotation.SuppressLint
import android.app.Activity
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Bundle
import android.webkit.PermissionRequest
import android.webkit.WebChromeClient
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebSettings
import android.webkit.WebView
import android.webkit.WebViewClient
import android.widget.TextView
import java.io.ByteArrayInputStream
import java.io.IOException
import java.net.HttpURLConnection
import java.net.URL

/**
 * The mark, and the reader.
 *
 * # Why a WebView and not a Canvas
 *
 * The art is one HTML file that the desktop, the server and this app all show.
 * Re-implementing a burning book, fourteen turning leaves and a QR encoder in
 * Kotlin would be a second implementation of something already written, which
 * is the rule this project states out loud about the forward pass -- and it is
 * not weaker for a picture. A WebView shows *those bytes*.
 *
 * # Why the origin is `https://chaos.invalid`
 *
 * **The reader needs a camera, and a browser refuses one outside a secure
 * context.** A node on a LAN is reached at `http://192.168.x.x:8080`, which is
 * not secure and never will be, so a WebView pointed straight at it can show
 * the mark but can never open the camera -- silently, with the same failure as
 * a missing permission.
 *
 * So the page is served to the WebView over an `https://` URL this app answers
 * itself, in [shouldInterceptRequest]. `.invalid` is the reserved TLD from
 * RFC 2606: it is guaranteed never to resolve, so this origin cannot collide
 * with a real host and a request that somehow escaped the interceptor fails
 * rather than reaching a stranger.
 *
 * This is `WebViewAssetLoader`'s trick without `androidx.webkit`. The APK has
 * no dependencies, on purpose, and this is twenty lines.
 *
 * # Where the bytes come from
 *
 * **Assets first, then the node.** A release APK carries the two pages under
 * `assets/brand/`, generated by `chaos-serve --emit-pages` so there is no
 * second copy of the wrapping logic to drift. A plain `gradlew assemble` with
 * no Rust build has no assets, and then the interceptor fetches the page from
 * whichever node the app is pointed at -- which works for the mark always, and
 * for the reader whenever there is a node.
 *
 * The order matters for the reader specifically: you scan a code in order to
 * *find* a node, so a reader that needs one first is a reader that cannot do
 * its job. Only the bundled asset makes it work from nothing.
 */
class BrandActivity : Activity() {

    private lateinit var web: WebView
    private lateinit var note: TextView

    /** `qr` or `scan`. */
    private var which: String = PAGE_MARK

    /** e.g. `http://192.168.1.20:8080`, or empty when the app has no node. */
    private var node: String = ""

    private var pendingCamera: PermissionRequest? = null

    @SuppressLint("SetJavaScriptEnabled")
    override fun onCreate(saved: Bundle?) {
        super.onCreate(saved)
        setContentView(R.layout.activity_brand)
        which = intent.getStringExtra(EXTRA_PAGE) ?: PAGE_MARK
        node = normalise(intent.getStringExtra(EXTRA_NODE) ?: "")

        note = findViewById(R.id.brand_note)
        web = findViewById(R.id.brand_web)
        web.settings.javaScriptEnabled = true
        // The pages are one screen that draws itself to the viewport; a
        // desktop-width layout scaled down would put the circle off the edge.
        web.settings.loadWithOverviewMode = false
        web.settings.useWideViewPort = false
        // Nothing is fetched, so nothing benefits from a cache, and a stale
        // copy of the mark would carry a stale route.
        web.settings.cacheMode = WebSettings.LOAD_NO_CACHE
        web.settings.mediaPlaybackRequiresUserGesture = false
        web.setBackgroundColor(0)

        web.webViewClient = object : WebViewClient() {
            override fun shouldInterceptRequest(
                view: WebView,
                request: WebResourceRequest,
            ): WebResourceResponse? = serve(request.url)

            override fun shouldOverrideUrlLoading(
                view: WebView,
                request: WebResourceRequest,
            ): Boolean {
                // The mark shows where its code leads, as a real link. Tapping
                // it should leave the app rather than replace the mark with a
                // page this WebView was not built for.
                val url = request.url
                if (url.host == ORIGIN_HOST) return false
                startActivity(Intent(Intent.ACTION_VIEW, url))
                return true
            }
        }

        web.webChromeClient = object : WebChromeClient() {
            /**
             * The camera, asked for by the page and granted by the app.
             *
             * Two separate permissions have to line up: Android's, held by this
             * process, and the WebView's, held per page. Granting only the
             * second produces a page that thinks it has a camera and gets a
             * black frame.
             */
            override fun onPermissionRequest(request: PermissionRequest) {
                if (!request.resources.contains(PermissionRequest.RESOURCE_VIDEO_CAPTURE)) {
                    runOnUiThread { request.deny() }
                    return
                }
                if (hasCamera()) {
                    runOnUiThread { request.grant(request.resources) }
                } else {
                    pendingCamera = request
                    requestPermissions(arrayOf(Manifest.permission.CAMERA), REQ_CAMERA)
                }
            }
        }

        // Asked before the page loads, so the reader does not have to fail once
        // to trigger the prompt.
        if (which == PAGE_SCRY && !hasCamera()) {
            requestPermissions(arrayOf(Manifest.permission.CAMERA), REQ_CAMERA)
        }

        note.text = when {
            which == PAGE_SCRY -> getString(R.string.brand_note_scan)
            node.isEmpty() -> getString(R.string.brand_note_no_node)
            else -> getString(R.string.brand_note_mark, node)
        }

        // The endpoint travels in the URL because that is one of the three ways
        // the page already resolves a route, and the only one available to a
        // page whose own origin is deliberately fictitious.
        val suffix = if (node.isEmpty()) "" else "?endpoint=" + Uri.encode(node)
        web.loadUrl("https://$ORIGIN_HOST/$which$suffix")
    }

    override fun onRequestPermissionsResult(
        code: Int,
        permissions: Array<out String>,
        granted: IntArray,
    ) {
        if (code != REQ_CAMERA) return
        val ok = granted.isNotEmpty() && granted[0] == PackageManager.PERMISSION_GRANTED
        pendingCamera?.let { req ->
            pendingCamera = null
            if (ok) req.grant(req.resources) else req.deny()
        }
        if (!ok && which == PAGE_SCRY) {
            note.text = getString(R.string.brand_note_no_camera)
        }
    }

    override fun onDestroy() {
        // A WebView left holding a camera keeps the indicator lit and the
        // device warm after the screen is gone.
        web.loadUrl("about:blank")
        web.destroy()
        super.onDestroy()
    }

    private fun hasCamera(): Boolean =
        checkSelfPermission(Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED

    /**
     * Answer one request for the fictitious origin: the bundled asset if the
     * APK carries one, otherwise the same path fetched from the node.
     *
     * Returning `null` lets the WebView do what it would have done, which for
     * an origin that cannot resolve is fail -- correct for a request neither
     * source can satisfy, and better than an empty 200 that renders as a blank
     * screen with no explanation.
     */
    private fun serve(url: Uri): WebResourceResponse? {
        if (url.host != ORIGIN_HOST) return null
        val page = when (url.path?.trimStart('/')) {
            PAGE_MARK, "mark" -> PAGE_MARK
            PAGE_SCRY -> PAGE_SCRY
            else -> return null
        }
        bundled(page)?.let { return html(it) }
        return fromNode(page)?.let { html(it) }
    }

    private fun bundled(page: String): ByteArray? = try {
        assets.open("brand/$page.html").use { it.readBytes() }
    } catch (_: IOException) {
        null
    }

    private fun fromNode(page: String): ByteArray? {
        if (node.isEmpty()) return null
        return try {
            val c = URL("$node/$page").openConnection() as HttpURLConnection
            c.connectTimeout = 4000
            c.readTimeout = 8000
            try {
                if (c.responseCode != 200) null else c.inputStream.use { it.readBytes() }
            } finally {
                c.disconnect()
            }
        } catch (_: Exception) {
            null
        }
    }

    private fun html(bytes: ByteArray) =
        WebResourceResponse("text/html", "utf-8", ByteArrayInputStream(bytes))

    companion object {
        const val EXTRA_PAGE = "page"
        const val EXTRA_NODE = "node"
        const val PAGE_MARK = "qr"
        const val PAGE_SCRY = "scan"

        private const val ORIGIN_HOST = "chaos.invalid"
        private const val REQ_CAMERA = 71

        /**
         * Make whatever is in the address box into an origin.
         *
         * The box accepts `192.168.1.20:8080` as readily as a full URL, and a
         * trailing slash from a paste is normal. Both have to be gone before
         * this is concatenated with a path.
         */
        fun normalise(raw: String): String {
            var s = raw.trim().trimEnd('/')
            if (s.isEmpty()) return ""
            if (!s.startsWith("http://") && !s.startsWith("https://")) s = "http://$s"
            // The address box holds an OpenAI base URL, which conventionally
            // ends in `/v1`; the pages are not under it.
            if (s.endsWith("/v1")) s = s.dropLast(3)
            return s.trimEnd('/')
        }

        fun open(from: Activity, page: String, node: String) {
            from.startActivity(
                Intent(from, BrandActivity::class.java)
                    .putExtra(EXTRA_PAGE, page)
                    .putExtra(EXTRA_NODE, node),
            )
        }
    }
}
