"""Re-cut `assets/grimoire/fonts.css` from Google Fonts.

The brand pages typeset in Cinzel, IBM Plex Mono and UnifrakturMaguntia. When
those are `<link>`ed they are the only thing in the whole product that reaches
the network, and on the two machines that matter most -- one with no internet,
one reachable only over a LAN -- the link fails silently to a system serif.
So the faces are embedded, and this is the script that embeds them.

Latin subsets only: every rune in the pages is drawn as strokes, never typeset,
so nothing outside Basic Latin is ever asked for. Licences and the copyright
notices the OFL requires are in `assets/grimoire/fonts/NOTICE`.

    python scripts/embed-fonts.py
"""

import base64, re, subprocess, sys, pathlib

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")

def get(url, binary=False):
    out = subprocess.run(["curl", "-sL", "-m", "40", "-A", UA, url],
                         capture_output=True)
    if out.returncode != 0:
        sys.exit("curl failed for %s: %s" % (url, out.stderr[:200]))
    return out.stdout if binary else out.stdout.decode("utf-8")

FAMS = ("family=Cinzel:wght@400;500;600"
        "&family=IBM+Plex+Mono:wght@400;500"
        "&family=UnifrakturMaguntia")
css = get("https://fonts.googleapis.com/css2?" + FAMS + "&display=swap")

# Keep only the `latin` subset of each face: the pages draw runes as strokes,
# never as glyphs, so nothing outside Basic Latin is ever typeset.
blocks = re.findall(r"/\*\s*(\S+)\s*\*/\s*@font-face\s*\{(.*?)\}", css, re.S)
faces = []
for subset, body in blocks:
    if subset != "latin":
        continue
    fam = re.search(r"font-family:\s*'([^']+)'", body).group(1)
    wt = re.search(r"font-weight:\s*(\d+)", body).group(1)
    url = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)
    faces.append((fam, wt, url))

if len(faces) != 6:
    sys.exit("expected 6 latin faces, got %d: %r" % (len(faces), [(f, w) for f, w, _ in faces]))

out = ["/* Cinzel, IBM Plex Mono and UnifrakturMaguntia, latin subsets, embedded.",
       "   Generated by scripts/embed-fonts.py -- see assets/grimoire/fonts/NOTICE.",
       "   The served page fetches nothing: Chaos downloads nothing on its own,",
       "   and a page that reached out to a font CDN would be the one place in",
       "   the product that broke that. */"]
total = 0
for fam, wt, url in faces:
    raw = get(url, binary=True)
    total += len(raw)
    b64 = base64.b64encode(raw).decode("ascii")
    out.append("@font-face{font-family:'%s';font-style:normal;font-weight:%s;"
               "font-display:block;src:url(data:font/woff2;base64,%s) format('woff2');}"
               % (fam, wt, b64))
    print("%-22s %s  %6d bytes" % (fam, wt, len(raw)))

dest = pathlib.Path(__file__).resolve().parent.parent / "assets" / "grimoire" / "fonts.css"
dest.write_text("\n".join(out) + "\n", encoding="utf-8")
print("\nwoff2 total %d bytes -> %s (%d bytes with base64)" % (total, dest, dest.stat().st_size))
