"""Build assets/knob.svg and assets/mode-dial.svg.

The knob's centre is Atur's own `assets/logo.svg`, embedded rather than
redrawn -- the mark is his and is never substituted or approximated.

Run: python tools/make-mode-dial.py
"""
import io
import pathlib
import re

ROOT = pathlib.Path(r'C:\Projects\Bigtea')
LOGO = ROOT / 'assets' / 'logo.svg'

# --- the logo, as a group we can scale into a circle --------------------------
raw = LOGO.read_text(encoding='utf-8')
inner = raw.split('>', 2)[2]                      # past <?xml ...?> and <svg ...>
inner = inner.rsplit('</svg>', 1)[0].strip()

# The first path is the full-canvas white background. Keep it: it becomes the
# face of the boss, so the mark sits on white exactly as drawn.
LOGO_W, LOGO_H = 1048, 1008


def logo_group(cx, cy, diameter, clip_id):
    s = diameter / max(LOGO_W, LOGO_H)
    tx = cx - (LOGO_W * s) / 2
    ty = cy - (LOGO_H * s) / 2
    return (
        f'  <g clip-path="url(#{clip_id})">\n'
        f'    <g transform="translate({tx:.3f},{ty:.3f}) scale({s:.6f})">\n'
        f'{inner}\n'
        f'    </g>\n'
        f'  </g>\n'
    )


DEFS = """  <defs>
    <radialGradient id="body" cx="38%" cy="30%" r="74%">
      <stop offset="0%"   stop-color="#ffffff"/>
      <stop offset="40%"  stop-color="#f8f8f6"/>
      <stop offset="70%"  stop-color="#e7e7e3"/>
      <stop offset="89%"  stop-color="#d2d2cd"/>
      <stop offset="100%" stop-color="#bcbcb7"/>
    </radialGradient>

    <radialGradient id="skirt" cx="44%" cy="38%" r="72%">
      <stop offset="0%"   stop-color="#ededea"/>
      <stop offset="55%"  stop-color="#dcdcd7"/>
      <stop offset="85%"  stop-color="#b6b6b0"/>
      <stop offset="100%" stop-color="#96968f"/>
    </radialGradient>

    <linearGradient id="bezel" x1="18%" y1="2%" x2="82%" y2="98%">
      <stop offset="0%"   stop-color="#ffffff"/>
      <stop offset="30%"  stop-color="#fbfbf9"/>
      <stop offset="62%"  stop-color="#cdcdc7"/>
      <stop offset="100%" stop-color="#a4a49e"/>
    </linearGradient>

    <linearGradient id="collar" x1="20%" y1="0%" x2="80%" y2="100%">
      <stop offset="0%"   stop-color="#d8d8d3"/>
      <stop offset="45%"  stop-color="#f2f2ef"/>
      <stop offset="100%" stop-color="#9e9e98"/>
    </linearGradient>

    <linearGradient id="gloss" x1="0%" y1="0%" x2="55%" y2="100%">
      <stop offset="0%"   stop-color="#ffffff" stop-opacity="0.95"/>
      <stop offset="55%"  stop-color="#ffffff" stop-opacity="0.25"/>
      <stop offset="100%" stop-color="#ffffff" stop-opacity="0"/>
    </linearGradient>

    <radialGradient id="shadow" cx="50%" cy="50%" r="50%">
      <stop offset="0%"   stop-color="#000000" stop-opacity="0.38"/>
      <stop offset="58%"  stop-color="#000000" stop-opacity="0.17"/>
      <stop offset="100%" stop-color="#000000" stop-opacity="0"/>
    </radialGradient>

    <linearGradient id="ridge" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%"   stop-color="#ffffff" stop-opacity="0.90"/>
      <stop offset="42%"  stop-color="#ffffff" stop-opacity="0.12"/>
      <stop offset="58%"  stop-color="#000000" stop-opacity="0.14"/>
      <stop offset="100%" stop-color="#000000" stop-opacity="0.34"/>
    </linearGradient>

    <clipPath id="bossClip">
      <circle cx="256" cy="256" r="86"/>
    </clipPath>
  </defs>
"""


def knurl(n=48, y=48, h=34, w=7.0):
    """A ring of rounded ridges. Two rings, offset, read as a real knurl."""
    out = [f'  <g id="knurl">\n'
           f'    <rect x="{256 - w/2:.2f}" y="{y}" width="{w}" height="{h}" '
           f'rx="{w/2:.2f}" fill="url(#ridge)"/>\n  </g>\n']
    step = 360.0 / n
    for i in range(1, n):
        out.append(f'  <use href="#knurl" transform="rotate({i*step:.4g} 256 256)"/>\n')
    return ''.join(out)


KNOB = f'''<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by tools/make-mode-dial.py. Do not edit by hand.

  The mode knob: a gas-stove control, white, that chooses what this machine is
  to the others. Four detents, matching the four CHAOS roles.

  The centre is `assets/logo.svg`, embedded rather than redrawn. The mark is
  Atur's and is never substituted, approximated or regenerated.

  Drawn centred with the pointer at 12 o'clock, so selecting a detent is one
  rotation about the middle of the image.
-->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg"
     width="512" height="512" viewBox="0 0 512 512">
{DEFS}
  <ellipse cx="256" cy="288" rx="214" ry="208" fill="url(#shadow)"/>

  <circle cx="256" cy="256" r="206" fill="url(#skirt)"/>
{knurl()}
  <circle cx="256" cy="256" r="206" fill="none" stroke="#00000024" stroke-width="3"/>

  <circle cx="256" cy="256" r="172" fill="url(#bezel)"/>
  <circle cx="256" cy="256" r="160" fill="url(#body)"/>
  <circle cx="256" cy="256" r="136" fill="none" stroke="#00000010" stroke-width="2"/>

  <g>
    <rect x="248" y="96" width="16" height="92" rx="8" fill="#00000026"/>
    <rect x="249.5" y="94" width="13" height="90" rx="6.5" fill="#57575350"/>
    <rect x="249.5" y="94" width="4.5" height="90" rx="2.2" fill="#3c3c3980"/>
    <rect x="258" y="96" width="3" height="86" rx="1.5" fill="#ffffff" opacity="0.55"/>
  </g>

  <path d="M 152 152 A 148 148 0 0 1 256 108 L 256 132
           A 124 124 0 0 0 169 169 Z" fill="url(#gloss)"/>

  <circle cx="256" cy="256" r="96" fill="url(#collar)"/>
  <circle cx="256" cy="256" r="88" fill="#ffffff"/>
{logo_group(256, 256, 172, 'bossClip')}
  <circle cx="256" cy="256" r="88" fill="none" stroke="#00000022" stroke-width="2"/>
  <circle cx="256" cy="256" r="96" fill="none" stroke="#0000001a" stroke-width="1.5"/>
</svg>
'''

(ROOT / 'assets' / 'knob.svg').write_text(KNOB, encoding='utf-8', newline='')
print('assets/knob.svg')

# The knob's markup, without its <svg> wrapper, for inlining into the plate.
KNOB_INNER = KNOB.split('viewBox="0 0 512 512">', 1)[1].rsplit('</svg>', 1)[0]

# --- the plate ---------------------------------------------------------------
# **A 180 degree sweep across the top, not a full circle.** Atur: "I want the 4
# options to be on the top side of the circle, not 360 -- it must be 270 or 180
# for this 4-option circle movement." A stove knob sweeps an arc and stops; it
# does not spin. So the four detents sit at -90, -30, +30 and +90 from twelve
# o'clock, 60 degrees apart, and the knob's travel has two ends.
#
# Left to right is a ramp of involvement, the way a stove goes OFF to HIGH:
# ALONE (nothing reaches this machine) through to CORE (it serves everyone).
#
# **No dark plate.** Atur: "just white circle is ok, we do not need that black
# colour." The background is transparent, so each app paints it in its own
# theme and the knob's own shadow does the separating.
MODES = [
    (-90, 'ALONE',  'only this machine'),
    (-30, 'CLIENT', 'uses a CORE elsewhere'),
    (30,  'HELPER', 'lends memory and cores'),
    (90,  'CORE',   'holds the models, answers others'),
]

# Which detent the preview shows the knob turned to. ALONE is the default a
# fresh install starts on; CORE is the one worth looking at.
PREVIEW = 90

import math

CX, CY = 320, 330
ticks, labels = [], []
for ang, name, _ in MODES:
    a = math.radians(ang - 90)
    for r0, r1, wdt, col in ((248, 268, 6, '#4a4a47'), (272, 280, 3, '#9a9a95')):
        x0, y0 = CX + r0 * math.cos(a), CY + r0 * math.sin(a)
        x1, y1 = CX + r1 * math.cos(a), CY + r1 * math.sin(a)
        ticks.append(f'  <line x1="{x0:.2f}" y1="{y0:.2f}" x2="{x1:.2f}" y2="{y1:.2f}" '
                     f'stroke="{col}" stroke-width="{wdt}" stroke-linecap="round"/>\n')
    lx, ly = CX + 296 * math.cos(a), CY + 296 * math.sin(a)
    if ang == -90:
        anchor, dy = 'end', '0.34em'
    elif ang == 90:
        anchor, dy = 'start', '0.34em'
    else:
        anchor, dy = 'middle', '-0.3em'
    labels.append(f'  <text x="{lx:.1f}" y="{ly:.1f}" text-anchor="{anchor}" dy="{dy}" '
                  f'font-family="Segoe UI, Inter, system-ui, sans-serif" font-size="27" '
                  f'font-weight="600" letter-spacing="3" fill="#26262b">{name}</text>\n')

# The arc the pointer travels, drawn faintly so the two ends are visible.
a0, a1 = math.radians(-180), math.radians(0)
ax0, ay0 = CX + 238 * math.cos(a0), CY + 238 * math.sin(a0)
ax1, ay1 = CX + 238 * math.cos(a1), CY + 238 * math.sin(a1)
sweep = (f'  <path d="M {ax0:.2f} {ay0:.2f} A 238 238 0 0 1 {ax1:.2f} {ay1:.2f}" '
         f'fill="none" stroke="#00000014" stroke-width="10" stroke-linecap="round"/>\n')

KNOB_INNER = KNOB.split('viewBox="0 0 512 512">', 1)[1].rsplit('</svg>', 1)[0]

DIAL = f'''<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by tools/make-mode-dial.py. Do not edit by hand.

  The mode control, as the launch screen shows it. Four detents across the top
  in a 180 degree sweep, because a stove knob travels an arc and stops rather
  than spinning: the two ends are ALONE and CORE.

  The background is transparent on purpose. Each app paints its own, and the
  knob's shadow is what separates it.

  The centre is assets/logo.svg, embedded rather than redrawn.
-->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg"
     width="640" height="640" viewBox="0 0 640 640">

{{sweep}}{{ticks}}{{labels}}
  <g transform="translate({{kx}},{{ky}}) rotate({{rot}} 256 256)">
{{knob}}
  </g>
</svg>
'''
DIAL = (DIAL
        .replace('{sweep}', sweep)
        .replace('{ticks}', ''.join(ticks))
        .replace('{labels}', ''.join(labels))
        .replace('{kx}', str(CX - 256))
        .replace('{ky}', str(CY - 256))
        .replace('{rot}', str(PREVIEW))
        .replace('{knob}', KNOB_INNER))
(ROOT / 'assets' / 'mode-dial.svg').write_text(DIAL, encoding='utf-8', newline='')
print('assets/mode-dial.svg')
